### ISSUE TITLE
Format the user stories

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#109]
Format all of the user stories in accordance to how user story for the login is formatted (see issue #8).

Most of the work should already be done but the tasks need to be linked to issues.

**Comment by SalmaAl22** [comment]
**you want a title format, or want me to work on the content of each issue? 

if you want me to work on the content, should it be like:** 

1) TO DO:
Create login page where user must input email address and password -- Page must include a button for creating a new account
Link the page to the database such that inputing an inexistent account doesn't work

OR

2)User Story: As a user, I want to be able to log into the website

Associated Tasks:

Create the log in page where the user can input email address and password to login (Issue https://github.com/wam82/teamname-soen341project2023/issues/59)
Create necessary DB tables such that a given email and password combination can be verified for authentication (Issue https://github.com/wam82/teamname-soen341project2023/issues/60)
Story point:
5 - The login page has fiew fields to be implemented the challenge comes in the backend when verifying the validity of an account for authentication

Priority:
MED - Is a feature necessary for the final product but is not depended on by any other features

Risk:
HIGH - User can input any data they want such as a command to take control of the database if they were to have malicious intents

Countermeasure:
A max character limit could be implemented in the context of a professional project in order to prevent malicious users
