### ISSUE TITLE
Refer candidates

### ISSUE THREAD

**Issue by AA789-ai** [wam82/teamname-soen341project2023#36]
User should be able to refer candidates to employers once this issue is resolved.

**Comment by Amir8Abdullah** [comment]
User Story: As a headhunter I should be able to refer candidates to employers once this issue is resolved.

Associated Tasks:
- Database for user accounts connected, configured and deployed.
- Database for job postings connected, configured and deployed
- Database for job applications connected, configured and deployed.

Story point:

Priority:
LOW - Is a feature necessary for the functionality for headerdunter, but it does not affect the functionality of employer, students and admin.

Risk:
LOW - Not having headerhunter implemented does not affect students ability to apply for jobs and employers to post their job postings.

**Comment by wam82** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-cf3f7f14-7fff-d2b9-6948-3c0741b3da26"><div dir="ltr" style="margin-left:0pt;" align="left">

Tested Requirement | Refer candidates for jobs
-- | --
Quick Description | Once on a specific job posting of an employer: The head hunter must be able to see all the applicants and click the ‘recommend’ button to recommend students to the employer.
Prerequisite | Database for user accounts connected, configured and deployed. Database for job postings connected, configured and deployed Database for job applications connected, configured and deployed. The user must be a ‘HEADHUNTER’ type account.
Input | Specific job post page, click to ‘recommend button’
Expected Output | The button must display ‘recommended’. The employer must receive the recommendations of users. In job posting application recommendation, the student id must be appended.
Observed Output | When the user presses recommend, the button updates to recommended and a request is sent to the database
Verdict | Passed
Comments |  

</div></b>
